name: urnavotos
description: Aplicativo para criação de enquetes.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  brasil_fields: ^1.6.0
  http: ^0.13.5
  flutter_dotenv: ^5.0.2
  snippet_coder_utils: ^1.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true
  fonts:
    - family: Vermin-Vibes
      fonts:
        - asset: assets/fonts/Vermin-Vibes.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter.ttf

  #assets:
    #- .env

