name: urnavotos
description: Aplicativo para criação de enquetes.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  get: ^4.6.5
  flutter:
    sdk: flutter

  intl: ^0.17.0
  provider: ^6.0.4
  cupertino_icons: ^1.0.2
  brasil_fields: ^1.6.0
  http: ^0.13.5
  shared_preferences: ^2.0.15
  flutter_dotenv: ^5.0.2
  get_it: ^7.2.0
  dio: ^4.0.6
  syncfusion_flutter_charts: ^20.3.60

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  assets:
    - assets/images/
    - .env
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.

  uses-material-design: true
  fonts:
    - family: Vermin-Vibes
      fonts:
        - asset: assets/fonts/Vermin-Vibes.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter.ttf



